### ISSUE TITLE
Customized error pages

### ISSUE THREAD

**Issue by maxbeckers** [BitBagCommerce/OpenMarketplace#1]
Error pages have the default symfony layout atm. This morining I called https://demo.open-marketplace.io/admin/product-listings/?sorting%5Bvendor%5D=desc&page=1 and got an error 500. But it's the same in shop Frontent with 404 errors for example when calling https://demo.open-marketplace.io/en_US/taxons/for-home/gardeningX .

![Screenshot 2022-10-25 130814](https://user-images.githubusercontent.com/11738128/197758714-ade1ce96-fa44-43c4-a5ac-8aed40bdce01.png)

There should be a custom error page handling with a proper design. For more details, how to create the template see https://symfony.com/doc/current/controller/error_pages.html .

**Comment by senghe** [comment]
Hi @maxbeckers 

Thanks for the issue! :) I agree that's something that should be implemented in our project. I'm adding the task to our board and be back when have more details :)

**Comment by senghe** [comment]
It's merged, so I'm closing the issue :ok_hand:

**Comment by senghe** [comment]
It's been closed by missclick :sweat_smile:

**Comment by senghe** [comment]
The error pages have been added to our 2.0 roadmap :tada: https://github.com/orgs/BitBagCommerce/projects/1

**Comment by senghe** [comment]
We've merged the 404 and 500 pages :tada: 

![image](https://github.com/BitBagCommerce/OpenMarketplace/assets/2512726/9f8ced80-10b9-4660-aede-8dcf0867acaa)

It'll be released with some other fun stuff. So I'm closing the issue :sparkles:
