### ISSUE TITLE
The default fixtures are unloadable

### ISSUE THREAD

**Issue by rimas-kudelis** [BitBagCommerce/OpenMarketplace#109]
The fixture files in `%kernel.project_dir%/src/Resources/config/fixtures/` refer to images under `%kernel.project_dir%/var/fixtures/`, but these files aren't committed and don't seem to exist in any of the vendor packages either. This causes `sylius:fixtures:load` to exit early, without loading all fixtures when starting the `migrations` container:
```
migrations        | In FileLocator.php line 44:
migrations        |
migrations        |   The file "/srv/open_marketplace/var/fixtures/images/vendor/background-image
migrations        |   /1.jpg" does not exist.
migrations        |
migrations        |
migrations        | sylius:fixtures:load [<suite>]
```

**Comment by senghe** [comment]
Hi, to load fixtures please use `bin/fixtures` command. It fetches the product images from our server.
