### ISSUE TITLE
Product listing pages are not responsive

### ISSUE THREAD

**Issue by Justin-Jordan** [BitBagCommerce/OpenMarketplace#11]
When i change the size of the window, the products doesn't go on their own row.  
As showed in the picture.
![Capture d’écran 2022-11-15 à 11 00 14](https://user-images.githubusercontent.com/61962136/201890785-51f366ee-80db-4594-9df8-86698b416463.png)

**Comment by rafalmal** [comment]
Responsiveness has been added recently.
