### ISSUE TITLE
CMS pages have error

### ISSUE THREAD

**Issue by codebach** [BitBagCommerce/OpenMarketplace#112]
https://demo.open-marketplace.io/en_US/blog/

Came across with `No route found` error on sections part on the CMS. It doesn't work also on the demo!

**Comment by Audax23** [comment]
Hi,
To access this page, you must use this route: [https://demo.open-marketplace.io/en_US/pages/blog]

**Comment by senghe** [comment]
Thanks guys for the issue and fast solving it! :) I think I cannot do anything more here except of closing the issue :ok_hand:
