### ISSUE TITLE
Error on M1

### ISSUE THREAD

**Issue by demoh2019** [BitBagCommerce/OpenMarketplace#115]
=> [migrations open_marketplace_node  3/17] RUN set -eux;  apk add --no-cache --virtual .build-deps   g++   gcc   make  ;      4.7s
 => CACHED [migrations composer 1/1] FROM docker.io/library/composer:2.4@sha256:0947196811261cab7cd05374a259f943e0215594c0f4bb  0.0s
 => CACHED [migrations php_extension_installer 1/1] FROM docker.io/mlocati/php-extension-installer:latest@sha256:24d3771f522eb  0.0s
 => [migrations base  2/23] RUN apk add --no-cache         acl         file         gettext         unzip     ;                 1.3s
 => [migrations base  3/23] COPY --from=php_extension_installer /usr/bin/install-php-extensions /usr/local/bin/                 0.0s
 => CANCELED [migrations base  4/23] RUN install-php-extensions apcu exif gd intl pdo_mysql opcache zip                        25.5s
 => [migrations open_marketplace_node  4/17] COPY package.json yarn.* ./                                                        0.0s
 => ERROR [migrations open_marketplace_node  5/17] RUN set -eux;     yarn install;     yarn cache clean                        21.5s

**Comment by senghe** [comment]
To be honest I don't know what do you mean by the message. I'm closing this issue, please reopen it when have better description.
