### ISSUE TITLE
Unused Argument?

### ISSUE THREAD

**Issue by codebach** [BitBagCommerce/OpenMarketplace#116]
I have found this argument set on service but never used in the Class itself:

Argument
https://github.com/BitBagCommerce/OpenMarketplace/blob/master/src/Component/Core/Vendor/Resources/services/form_types.xml#L99

Class:
https://github.com/BitBagCommerce/OpenMarketplace/blob/master/src/Component/Core/Vendor/Form/Type/ProductListing/ListingType.php

Can you please take a look?

**Comment by senghe** [comment]
Yup, it looks like a small refactoring bug. We'll remove this in a few days. Thanks a lot for your message! :vulcan_salute:
