### ISSUE TITLE
Order Products in admin Product listings

### ISSUE THREAD

**Issue by maxbeckers** [BitBagCommerce/OpenMarketplace#2]
When you go in admin backend to the product listings page and try to sort by the different colums there are a lot of 500 errors.

With the Release [1.0,4](https://github.com/BitBagCommerce/OpenMarketplace/releases/tag/v1.0.4) was fixed just the sort by `vendor`.

ATM only `id`, `code` and `vendor` are possible to sort. But `Name`, `Published At`, `Verified At` and `Status` have in Frontend as well the Buttons to sort. Using one of these columns to sort, there is as well a 500 Error.

![Screenshot 2022-10-27 071224](https://user-images.githubusercontent.com/11738128/198197435-8bfb13cb-15b2-4a53-88cd-8d2432641005.png)

**Comment by senghe** [comment]
Hi @maxbeckers!

Thanks for your the issue :) I've already fixed this on https://github.com/BitBagCommerce/OpenMarketplace/pull/5 and it should be released with the next version :crossed_fingers:
