### ISSUE TITLE
Missing Translations in admin messages filter

### ISSUE THREAD

**Issue by maxbeckers** [BitBagCommerce/OpenMarketplace#3]
There are missing translations for the admin messages filter, see the related screenshot:

![2022_10_27_07_18_00_Messages_BitBag_OpenMarketplace](https://user-images.githubusercontent.com/11738128/198198310-fded4a0e-d7de-4625-b6ba-04c281bdf702.png)

**Comment by senghe** [comment]
Hi @maxbeckers,

Thanks for the issue! :) It's already fixed in https://github.com/BitBagCommerce/OpenMarketplace/pull/6, so when build passes, I'm merging it into master :sweat:

**Comment by senghe** [comment]
It's merged, so I'm closing the issue :ok_hand:
