### ISSUE TITLE
Sorting of the admin catalog promotions not working

### ISSUE THREAD

**Issue by maxbeckers** [BitBagCommerce/OpenMarketplace#4]
In the admin backend the sorting of the catalog promotions does not work. Clicking to sort by one column kust reloads the page, but no sorting. And the sort order is as well not added to the url. So this seems to be a frontend bug.

![Screenshot 2022-10-27 072406](https://user-images.githubusercontent.com/11738128/198198996-1da1c687-93c6-46d8-b425-093083db7299.png)

**Comment by senghe** [comment]
Hi @maxbeckers!

Thanks for the issue :) To be honest, the part of project you've already tested comes directly from Sylius and is not customized in any part by OpenMarketplace. I encourage you to submit the issue into Sylius repository :)
