### ISSUE TITLE
Manage product variants

### ISSUE THREAD

**Issue by lapnd** [BitBagCommerce/OpenMarketplace#63]
Hi,
I have a question. 
- If I understand correctly, each vendor creates product listing with variants. For example, they want to provide T-Shirt with different color/size. This work should be done under a vendor accounts, not System Administration accounts.
- However, in the Openmarketplace, when login as vendor, I haven't figured out where to define product variants. The product variants are managed under System Administration accounts only.
Could you please let me know if my understanding is incorrect?

**Comment by senghe** [comment]
Hi. OpenMarketplace currently supports only single-variant products. This means you need to create two product listings for similar products with different options.
