### ISSUE TITLE
Create a CONTRIBUTE.md for external contributors

### ISSUE THREAD

**Issue by maxbeckers** [BitBagCommerce/OpenMarketplace#9]
Hi,

I already asked the Question and in Slack channel was also the question how to contibute.

Would be very great to have a `CONTRIBUTE.md` file where is described how to contribute.

There might be as well a few more things to do to have a low hurdle for external contributors like an issue template, ...

**Comment by rafalmal** [comment]
Created PR for CONTRIBUTE.md. https://github.com/BitBagCommerce/OpenMarketplace/pull/95

**Comment by senghe** [comment]
I see the file you asked about has been merged some time ago. So I'm closing the issue :vulcan_salute:
