### ISSUE TITLE
Installation Question 

### ISSUE THREAD

**Issue by aljawaid** [BitBagCommerce/OpenMarketplace#94]
The slack link is invalid so I can't ask there.

Would this software be good to create multiple storefronts for a community of small shops and stalls like a bazaar?

The demo doesn't show any storefronts or sorting by shops.

Also, can installation not work if all the setup files are uploaded to the server? Is there no Web based installation?

**Comment by senghe** [comment]
Hi,

OpenMarketplace is built on Sylius, which supports multichanneling. You can create products and product listings for different sales channel. Depending on your needs, you would need more or less development for some customization, as Sylius and OpenMarketplace mission is to be a framework.

Unfortunately we have no web based installation. There is a set of commands, which need to be executed and some steps for configuration. For the documentation please visit `doc/` folder in the project repository.
